project:
  type: book
  output-dir: "book"
bibliography: cites.bib
biblio-style: mla
link-citations: true
nocite: '@*'
csl: modern-language-association.csl
pdf-cover: "images/cover.pdf"
book:
  title: "i18n-check"
  author: "Blake Madden"
  date: today
  date-format: long
  language: en
  chapters:
    - index.qmd
    - building.qmd
    - part: "Command-line Utility"
      chapters:
      - command-line/options.qmd
      - command-line/samples.qmd
      - command-line/examples.qmd
    - cites.qmd
format:
  pdf:
    documentclass: book
    template: latex/default.tex
    include-in-header: latex/preamble.tex
    latex-engine: xelatex
    keep-tex: true
    citation-package: biblatex
    cite-method: biblatex
    lot: true
    code-block-bg: false
