project:
  type: book
  output-dir: "book"
bibliography: cites.bib
biblio-style: mla
link-citations: true
nocite: '@*'
csl: modern-language-association.csl
pdf-cover: "images/cover.jpg"
pdf-cover-author-color: "0, 0, 0"
pdf-cover-font-color: "255, 255, 255"
pdf-cover-color: "111, 144, 132"
book:
  title: "i18n-check"
  subtitle: "User Manual"
  description: "Internationalization & localization analysis system"
  author: "Blake Madden"
  date: today
  date-format: long
  language: en
  chapters:
    - index.qmd
    - building.qmd
    - part: "Command-line Utility"
      chapters:
      - command-line/options.qmd
      - command-line/examples.qmd
      - command-line/samples.qmd
    - part: "Graphical Interface"
      chapters: 
      - gui/options.qmd
    - part: "Additional Features"
      chapters:
      - suppression.qmd
    - cites.qmd
format:
  pdf:
    documentclass: book
    template: latex/default.tex
    include-in-header: latex/preamble.tex
    latex-engine: xelatex
    keep-tex: true
    citation-package: biblatex
    cite-method: biblatex
    lot: false
    code-block-bg: false
