name: Linux build
on: [push]

jobs:
  build:
    name: unix build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: install tools
        run: |
             sudo apt install cmake

      - name: build
        run: |
             cmake ./
             make -j4
 
      - name: analyze
        run: |
             # just analyze code formatting while we are here
             cd bin
             ./i18n-check ../src --ignore=cxxopts,utf8cpp --enable=allCodeFormatting -q -o i18nresults.txt

      - name: review results
        run: |
             cd bin
             REPORTFILE=./i18nresults.txt
             WARNINGSFILE=./warnings.txt
             if test -f "$REPORTFILE"; then
                cat "$REPORTFILE" > "$WARNINGSFILE"
                # are there any warnings?
                if grep -qP '\[[a-zA-Z0-9]+\]' "$WARNINGSFILE"; then
                    # print the remaining warnings
                    echo Warnings detected:
                    echo ==================
                    cat "$WARNINGSFILE" | grep -P '\[[a-zA-Z0-9]+\]'
                    # fail the job
                    exit 1
                else
                    echo No issues detected
                fi
             else
                echo "$REPORTFILE" not found
             fi
