name: unix build
on: [push]

jobs:
  build:
    name: unix build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: install tools
        run: |
             sudo apt install cmake
             sudo apt install lcov

      - name: build
        run: |
             cmake ./
             make -j4
